name: Make

on: 
  push:
    branches: 
    - master

jobs:
  make:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        # Use token to trigger Github Pages deployment on commit
        token: ${{ secrets.MY_GITHUB_TOKEN }}
    - run: |
        make
    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      name: Commit updates
      with:
        branch: master
        commit_message: |
          :alien: Make
          
          Sent from Github Actions (see .github/workflows/make.yml )
